### ISSUE TITLE
Get all items from RSS or Atom feed?

### ISSUE THREAD

**Issue by mskuratowski** [dotnet/SyndicationFeedReaderWriter#15]
Hi,

Is it possible to get all items from RSS or Atom feed? 

For example I have 

http://www.examplewebsite.com/feed/

and it returns only recent blog post (it is blog)

**Comment by drago-draganov** [comment]
@mskuratowski 

Microsoft.SyndicationFeed.ReaderWriter is forward looking API that doesn't cache the feed. To obtain all the feed items, you will need to keep reading the feed to the end and take action when the reader.ElementType is SyndicationElementType.Item. For example:

```cs
var reader = new RssFeedReader(xmlReader);

while (await reader.Read()) {
      //
      // Read items only
      if (reader.ElementType == SyndicationElementType.Item) {
          ISyndicationItem item = await reader.ReadItem();
          //
          // Process or cache the item as needed
          //
      }
}
```
