### ISSUE TITLE
Update Nuget package

### ISSUE THREAD

**Issue by chriswill** [dotnet/SyndicationFeedReaderWriter#16]
Hi, do you have a timeline for updating your nuget package based on the bug fixes for a month ago?

**Comment by jimmyca15** [comment]
@chriswill 

Early next week. I just sent out the PR for the version bump then we can build it and update the package.

**Comment by jimmyca15** [comment]
@chriswill 

The 1.0.1 package has been published. This features all of the bug fixes. A release doc is in the works.
