### ISSUE TITLE
RSS Feed do not parse categories

### ISSUE THREAD

**Issue by MaximRouiller** [dotnet/SyndicationFeedReaderWriter#19]
It seems that RSS Category parsing has been excluded.

Could we light up that features?

[RssParser](https://github.com/dotnet/SyndicationFeedReaderWriter/blob/master/src/Rss/RssParser.cs#L143) doesn't seem to do anything with individual item categories while [AtomParser](https://github.com/dotnet/SyndicationFeedReaderWriter/blob/master/src/Atom/AtomParser.cs#L255) does.

**Comment by jimmyca15** [comment]
@drago-draganov 

Seems we should add the category for RSS items. Looks like it was an an oversight.

**Comment by drago-draganov** [comment]
Indeed is an oversight.

**Comment by jimmyca15** [comment]
@drago-draganov 

@MaximRouiller is using the library and is blocked by the issue. We have the workaround available to [parse it as a custom element](https://github.com/dotnet/SyndicationFeedReaderWriter/blob/master/examples/ReadRssItemWithCustomFieldsExample.cs) but I think we can get this fixed quickly and ship 1.0.2 to unblock.

**Comment by drago-draganov** [comment]
Fixed in #20

**Comment by MaximRouiller** [comment]
@drago-draganov When should I expect a new package on Nuget?

**Comment by jimmyca15** [comment]
@MaximRouiller 

Just went live: https://www.nuget.org/packages/Microsoft.SyndicationFeed.ReaderWriter/1.0.2
