### ISSUE TITLE
RSS 1.0 support

### ISSUE THREAD

**Issue by Kwoth** [dotnet/SyndicationFeedReaderWriter#22]
Is there a plan, or an ETA on when will RSS 1.0 be supported?

**Comment by zhenlan** [comment]
@Kwoth we don't have a plan to support RSS 1.0 at this point.

This is currently achievable by user code using the extensibility points of the current release. To add built-in support of RSS 1.0, we would like to hear the demand from more customers.

For anyone comes across this thread in the future, if you also need the support of RSS 1.0, please
upvote (using 👍) on the first comment of this thread. We can reconsider it if this is highly demanded.

**Comment by Kwoth** [comment]
It's been a year and a half, any update on whether this will get added, and when?

**Comment by zhenlan** [comment]
Thanks for querying @Kwoth. Based on the demand and the priority of the team, there is no plan to add this support.
