### ISSUE TITLE
Samples: StringWriter UTF-8

### ISSUE THREAD

**Issue by natelaff** [dotnet/SyndicationFeedReaderWriter#24]
Fought for several days with the examples. Nothing I was doing was generating a valid feed. Finally it came down to the StringWriter outputting UTF-16 instead of UTF-8.

Did I miss something that should have made this easier? Just looking out for the next guy here who spins his wheels for days on the same issue.

**Comment by drago-draganov** [comment]
Good point, @natelaff!
Even though SyndicationFeedReaderWriter doesn't own the XmlWriter instance, we have to make sure the examples produce proper feeds (like these from the project [tests](https://github.com/dotnet/SyndicationFeedReaderWriter/blob/master/tests/RssWriter.cs)).

Thanks for bringing this up! I fixed the examples.
