### ISSUE TITLE
Invalid XML characters

### ISSUE THREAD

**Issue by daveaglick** [dotnet/SyndicationFeedReaderWriter#30]
When a feed contains invalid XML characters, the reader crashes. This isn't totally the fault of SyndicationFeedReaderWriter since the crash is coming from XmlReader, but it's not a great experience. This can be seen at http://cmatskas.com/rss/ which produces the following error:

```
'', hexadecimal value 0x0B, is an invalid character. Line 386, position 28.
```

I've resolved this by streaming the content through a special `StreamReader` that strips out invalid XML characters first:

```
string feed = "http://cmatskas.com/rss/";
using (WebClient webClient = new WebClient())
{
  using (Stream stream = await webClient.OpenReadTaskAsync(feed))
  {
    using (StreamReader streamReader = new XmlStreamReader(stream))
    {
      using (XmlReader xmlReader = XmlReader.Create(streamReader, new XmlReaderSettings { Async = true }))
      {
        // ...
      }
    }
  }
}
```

```
public class XmlStreamReader : StreamReader
{
	public XmlStreamReader(Stream stream) : base(stream)
	{
	}

	public override int Peek()
	{
		int ch = 0;
		while (ch != -1)
		{
			ch = base.Peek();
			if (XmlConvert.IsXmlChar((char)ch))
			{
				return ch;
			}
			base.Read();
		}
		return ch;
	}

	public override int Read()
	{
		int ch = 0;
		while (ch != -1)
		{
			ch = base.Read();
			if (XmlConvert.IsXmlChar((char)ch))
			{
				return ch;
			}
		}
		return ch;
	}

	public override int Read(char[] buffer, int index, int count)
	{
		int i;
		for(i = index ; i < count ; i++)
		{
			int c = Read();
			if(c == -1)
			{
				break;
			}
			buffer[i] = (char)c;
		}
		return i - index;
	}
}
```

So two things:
* Is there something that could be done from within SyndicationFeedReaderWriter to automatically resolve this? Perhaps if `AtomFeedReader` and `RssFeedReader` had overloads that accepted a URI and we set up the `XmlReader` internally?
* If this is determined to be out of scope for SyndicationFeedReaderWriter then feel free to close the issue - at a minimum it'll serve as troubleshooting documentation for anyone else who stumbles on this.

**Comment by daveaglick** [comment]
I started to do a spike of an alternate constructor for `AtomFeedReader` and `RssFeedReader` that accepts a URL and sets up the `XmlReader` for the user. Before I do any further, this will require changing the API of those classes (and probably `XmlFeedReader`) to implement `IDisposable` so that the created `XmlReader` can be disposed. We could also use the same pattern as some of the other stream classes and let the `XmlFeedReader` dispose the passed-in `XmlReader` when it's disposed if the user wants it to.

Thoughts?

**Comment by jimmyca15** [comment]
Having the readers construct an XmlReader from a URI is out of scope. The most acceptable alternative would be offering helper methods for constructing XML readers for certain scenarios, but that is also an edge case. 

Thanks for the write up, if someone does encounter a similar issue, creating an xml reader that strips out the invalid characters as you did would be the best approach.
