### ISSUE TITLE
Support for media:thumbnail

### ISSUE THREAD

**Issue by StefDotmailer** [dotnet/SyndicationFeedReaderWriter#38]
I have tried the library on the BBC news feed: http://feeds.bbci.co.uk/news/rss.xml

containing the following item: 
```
        <item>
            <title><![CDATA[House of Fraser bought by Sports Direct for £90m]]></title>
            <description><![CDATA[Sports Direct's Mike Ashley promises to turn House of Fraser into the "Harrods of the High Street".]]></description>
            <link>https://www.bbc.co.uk/news/business-45140874</link>
            <guid isPermaLink="true">https://www.bbc.co.uk/news/business-45140874</guid>
            <pubDate>Fri, 10 Aug 2018 13:59:51 GMT</pubDate>
            <media:thumbnail width="1024" height="576" url="http://c.files.bbci.co.uk/1B27/production/_102915960_mike_ashley_fraser_getty.jpg"/>
        </item>
```

When I look at the `SyndicationItem` object, I cannot see the link to the image so I assume it is not parsed.

Can you please consider parsing that element, too? Thank you.

**Comment by zhenlan** [comment]
Hi @StefDotmailer can you parse it using the extensibility point like the example we had below?

https://github.com/dotnet/SyndicationFeedReaderWriter/blob/master/examples/ReadRssItemWithCustomFieldsExample.cs

**Comment by zhenlan** [comment]
Unless it's something de-facto standard (eg. used in majority rss feeds out there in public), I don't think we want to add non-standard tags to this repo, because anyone who doesn't use it will pay a "tax" for it.
